In [9]:
# implementing XNOR using neural network with one hidden layer and gradient descent

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# creating the dataset
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[1],[0],[0],[1]])

In [3]:
# defining the sigmoid function
def sigmoid(x):
    return 1/(1+np.exp(-x))

# defining the derivative of sigmoid function
def sigmoid_derivative(x):
    return x*(1-x)

In [5]:
# defining parameters
epoch = 10000
lr = 0.1
inputlayer_neurons = X.shape[1]
hiddenlayer_neurons = 2
output_neurons = 1

# initializing weights and bias
wh = np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh = np.random.uniform(size=(1,hiddenlayer_neurons))
wout = np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout = np.random.uniform(size=(1,output_neurons))

In [6]:
# training the model
for i in range(epoch):
    # forward propagation
    hidden_layer_input1 = np.dot(X,wh)
    hidden_layer_input = hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1 = np.dot(hiddenlayer_activations,wout)
    output_layer_input = output_layer_input1 + bout
    output = sigmoid(output_layer_input)
    
    # backpropagation
    E = Y-output
    slope_output_layer = sigmoid_derivative(output)
    slope_hidden_layer = sigmoid_derivative(hiddenlayer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr

In [7]:
# testing the model
print("The output for the given input is:")
print(output)

The output for the given input is:
[[0.94459204]
 [0.05047901]
 [0.05074595]
 [0.94552772]]


In [12]:
# converting the output to 0 and 1
for i in range(len(output)):
    if output[i] > 0.5:
        output[i] = 1
    else:
        output[i] = 0
    
# printing in the form of dataframe
df = pd.DataFrame({'Input':X[:,0],'Input2':X[:,1],'Output':output[:,0]})
df

Input  Input2  Output
0      0       0     1.0
1      0       1     0.0
2      1       0     0.0
3      1       1     1.0

In [13]:
# printing the hidden layer weights
print("The weights of the hidden layer are:")
print(wh)

The weights of the hidden layer are:
[[5.82467566 3.70219243]
 [5.91489814 3.72001063]]


In [15]:
# printing bias of hidden layer
print("The bias of the hidden layer is:")
print(bh)

The bias of the hidden layer is:
[[-2.46671469 -5.68646385]]


In [16]:
# printing the output layer weights
print("The weights of the output layer are:")
print(wout)

The weights of the output layer are:
[[-7.58629781]
 [ 8.27878372]]


In [18]:
# printing bias of output layer
print("The bias of the output layer is:")
print(bout)

The bias of the output layer is:
[[3.40157547]]


In [19]:
# printing the error
print("The error is:")
print(E)

The error is:
[[ 0.05540796]
 [-0.05047901]
 [-0.05074595]
 [ 0.05447228]]


In [21]:
# combining the input, output, error and prediction in a dataframe
df = pd.DataFrame({'Input':X[:,0],'Input2':X[:,1],'Output':output[:,0],'Error':E[:,0]})
df

Input  Input2  Output     Error
0      0       0     1.0  0.055408
1      0       1     0.0 -0.050479
2      1       0     0.0 -0.050746
3      1       1     1.0  0.054472